version: '3.8'

services:
  # Spring Boot application
  revlo:
    build: .
    container_name: revlo
    ports:
      - "8058:8060"  # Adjust as needed: host:container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5429/revlo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD= blessed
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - database
    networks:
      - app-network

  # PostgreSQL database
  database:
    container_name: postgres-revlo
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blessed
    ports:
      - "5429:5432"  # Expose PostgreSQL on port 5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
